// 1 - CRIAR USUARIO - OK

####
POST http://localhost:3306/user/signup
Content-Type: application/json

{
    "name": "John Bidden",
    "email": "president@labenu.com",
    "password": "123456",
    "role":"ADMIN"
}


// 2 - LOGIN - OK

####
GET http://localhost:3306/user/login
Content-Type: application/json

    {
        "email": "user@labenu.com",
        "password": "123456"
    }


// 3 - INFORMAÇÕES DO PERFIL - OK

####
GET http://localhost:3306/user/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ3NGM5YTBkLTRiMmMtNGZkYy05YzUwLWYyYTQzZjFhMjc5NCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzY1OTYzNzUsImV4cCI6MTY3NjU5OTk3NX0.CEHYoVEu3hs_Uxc3Q8wuYf8TWNNQk2qo6bLIahn9DZQ



// 4 - CRIAR RECEITA  - OK

###
POST http://localhost:3306/recipe
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkNDg5M2E2LWQ4YjItNGI2OC04NTViLTA0YzRiN2RjYTFlNiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3NjU0ODAxNCwiZXhwIjoxNjc2NTUxNjE0fQ.soI2qWR-YX3DGxW1EVz3duU5LQEeuUX-36m6Jih5z44

{
    "title": "Rocambole",
    "description": "Faz um bolo e enrola",
    "author_id":"7d4893a6-d8b2-4b68-855b-04c4b7dca1e6"
}


// 5 - SEGUIR USUÁRIO
####
GET http://localhost:3306/user/1675946504304
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkNDg5M2E2LWQ4YjItNGI2OC04NTViLTA0YzRiN2RjYTFlNiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3NjU0ODAxNCwiZXhwIjoxNjc2NTUxNjE0fQ.soI2qWR-YX3DGxW1EVz3duU5LQEeuUX-36m6Jih5z44


// 6 - BUSCA RECEITAS POR ID DO USUÁRIO, COM TOKEN - OK
####
GET http://localhost:3306/recipe/d74c9a0d-4b2c-4fdc-9c50-f2a43f1a2794
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ3NGM5YTBkLTRiMmMtNGZkYy05YzUwLWYyYTQzZjFhMjc5NCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzY1OTM5NDgsImV4cCI6MTY3NjU5NzU0OH0.bV7-TuE_lkR_9LNxrLxhV6_5imj5iUtxX81YaGoUbwE


//EXTRA - SEGUIR USUARIO - OK

###
POST http://localhost:3306/user/follow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBmY2QyMWU4LWMxODctNGY5ZS1iMjAwLTAzM2NlODQyZGM3MiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzY1NTk0ODMsImV4cCI6MTY3NjU2MzA4M30.qJ0Z63c7L1lXhf_ibuN7qe9Xm8Tb4stBQrVwySNykDU

{
   "friendId": "914f9701-8d69-4271-8b20-e0caae53fc15"
}


//EXTRA - DESFAZ AMIZADE - OK

###
DELETE  http://localhost:3306/user/unfollow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkNDg5M2E2LWQ4YjItNGI2OC04NTViLTA0YzRiN2RjYTFlNiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3NjU0ODAxNCwiZXhwIjoxNjc2NTUxNjE0fQ.soI2qWR-YX3DGxW1EVz3duU5LQEeuUX-36m6Jih5z44

{
    "friendId":"914f9701-8d69-4271-8b20-e0caae53fc15"
}


//BUSCAR FEED 

####
GET http://localhost:3306/user/feed
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ3NGM5YTBkLTRiMmMtNGZkYy05YzUwLWYyYTQzZjFhMjc5NCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzY1OTYzNzUsImV4cCI6MTY3NjU5OTk3NX0.CEHYoVEu3hs_Uxc3Q8wuYf8TWNNQk2qo6bLIahn9DZQ









//////////////////////         EXTRAS             //////////////////////  


//BUSCAR AMIGOS 

####
GET http://localhost:3306/user/friends/7d4893a6-d8b2-4b68-855b-04c4b7dca1e6
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ3NGM5YTBkLTRiMmMtNGZkYy05YzUwLWYyYTQzZjFhMjc5NCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzY1NjA1ODcsImV4cCI6MTY3NjU2NDE4N30.rPqWmzt5k_UXhkzDtsOQ-TQRDfyUW-6JHC9qm9P_Img








# //BUSCA RECEITA POR ID 

# ####
# GET http://localhost:3306/recipe/get/1675955467898
# Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkNDg5M2E2LWQ4YjItNGI2OC04NTViLTA0YzRiN2RjYTFlNiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3NjU0ODAxNCwiZXhwIjoxNjc2NTUxNjE0fQ.soI2qWR-YX3DGxW1EVz3duU5LQEeuUX-36m6Jih5z44


//BUSCA TODOS USUARIOS - OK

####
GET http://localhost:3306/user/getAll
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkNDg5M2E2LWQ4YjItNGI2OC04NTViLTA0YzRiN2RjYTFlNiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3NjU0ODAxNCwiZXhwIjoxNjc2NTUxNjE0fQ.soI2qWR-YX3DGxW1EVz3duU5LQEeuUX-36m6Jih5z44


# //CRIA AMIZADE

# ###
# POST http://localhost:3306/user/1674763316671
# Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkNDg5M2E2LWQ4YjItNGI2OC04NTViLTA0YzRiN2RjYTFlNiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3NjU0ODAxNCwiZXhwIjoxNjc2NTUxNjE0fQ.soI2qWR-YX3DGxW1EVz3duU5LQEeuUX-36m6Jih5z44


# //DESFAZ AMIZADE

# ###
# DELETE  http://localhost:3306/friend/delete
# Content-Type: application/json

# {
#     "friendId":"1674763316671"
# }






//  BUSCA TODAS AS RECEITAS COM TOKEN - OK

####
GET http://localhost:3306/recipe/getAll
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ3NGM5YTBkLTRiMmMtNGZkYy05YzUwLWYyYTQzZjFhMjc5NCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzY1NzQ2OTAsImV4cCI6MTY3NjU3ODI5MH0.Y7kIkhcUK5WbK7zehlnj2032SBTNiJNebWrWLvOgd04


